//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtGraViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PtGraViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [A4] not Exist in printer settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A4NotExist {
            get {
                return ResourceManager.GetString("A4NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t print any more. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CantPrintAnyMore {
            get {
                return ResourceManager.GetString("CantPrintAnyMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection closed by server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnClosed {
            get {
                return ResourceManager.GetString("ConnClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not establish connection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CouldntOpenConn {
            get {
                return ResourceManager.GetString("CouldntOpenConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file is being used. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileBeingUsed {
            get {
                return ResourceManager.GetString("FileBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are files with same name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNameDuplicated {
            get {
                return ResourceManager.GetString("FileNameDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder is not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderNotExist {
            get {
                return ResourceManager.GetString("FolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   has occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HasOccurred {
            get {
                return ResourceManager.GetString("HasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initial setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InitialSetting {
            get {
                return ResourceManager.GetString("InitialSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID is needed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoID {
            get {
                return ResourceManager.GetString("NoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not configured. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotConfigured {
            get {
                return ResourceManager.GetString("NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Out of memory exception has occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutOfMemory {
            get {
                return ResourceManager.GetString("OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Permission denied. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The setting file may be corrupt. Do you want to delete setting file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingFileBroken {
            get {
                return ResourceManager.GetString("SettingFileBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This file type is unsupported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnsupportedFileType {
            get {
                return ResourceManager.GetString("UnsupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can check until 8 pieces. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpperLimitIs8 {
            get {
                return ResourceManager.GetString("UpperLimitIs8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection string is wrong. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WrongConnectingString {
            get {
                return ResourceManager.GetString("WrongConnectingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WrongText {
            get {
                return ResourceManager.GetString("WrongText", resourceCulture);
            }
        }
    }
}
